# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandworm < Formula
  desc "Project file concatenator for Claude AI"
  homepage "https://github.com/holonoms/sandworm"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/holonoms/sandworm/releases/download/v0.1.3/sandworm_0.1.3_darwin_amd64.tar.gz"
      sha256 "d46cc7de3ad6cdc03cd3c3b293d2482f8e135d7b975c17148e40412a284165c9"

      def install
        bin.install "sandworm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/holonoms/sandworm/releases/download/v0.1.3/sandworm_0.1.3_darwin_arm64.tar.gz"
      sha256 "46ee17fd74cb5feedbec15927856285b5ce8af8abe0da2871e1f3a09d7dc2754"

      def install
        bin.install "sandworm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/holonoms/sandworm/releases/download/v0.1.3/sandworm_0.1.3_linux_amd64.tar.gz"
        sha256 "8c0dc2980c0229a91c966cef9f8f992c1cc61324cc4e6c9da7938230539f7754"

        def install
          bin.install "sandworm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/holonoms/sandworm/releases/download/v0.1.3/sandworm_0.1.3_linux_arm64.tar.gz"
        sha256 "2f83cc6bbecc272b67a0818c78aa3344cd2b0109da97c1797e829cd49864b16f"

        def install
          bin.install "sandworm"
        end
      end
    end
  end

  test do
    system "#{bin}/sandworm", "--version"
  end
end
