# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandworm < Formula
  desc "Project file concatenator for Claude AI"
  homepage "https://github.com/umwelt-studio/sandworm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umwelt-studio/sandworm/releases/download/v0.1.0/sandworm_0.1.0_darwin_amd64.tar.gz"
      sha256 "154a98f11afa919531621b523da43b86f785253c26eadfbaa98492f565202608"

      def install
        bin.install "sandworm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umwelt-studio/sandworm/releases/download/v0.1.0/sandworm_0.1.0_darwin_arm64.tar.gz"
      sha256 "cd771aa0b83e0d92c37c88e2650b36ebb08422aafeee85bc39805a1e7cb0dde4"

      def install
        bin.install "sandworm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umwelt-studio/sandworm/releases/download/v0.1.0/sandworm_0.1.0_linux_amd64.tar.gz"
        sha256 "8341bfb20913e9959bf8a8b2c461d87e0bde0a9cf9cebd57c7a6b9ea7e83f830"

        def install
          bin.install "sandworm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umwelt-studio/sandworm/releases/download/v0.1.0/sandworm_0.1.0_linux_arm64.tar.gz"
        sha256 "e7c035b5925a302a6ccb876f838f9da7a999a87f8800593780299817e4a07b0a"

        def install
          bin.install "sandworm"
        end
      end
    end
  end

  test do
    system "#{bin}/sandworm", "--version"
  end
end
